name: CodeCov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "2"

      - name: Checkout diffraction_utils
        uses: actions/checkout@v4
        with:
          repository: DiamondLightSource/diffraction_utils
          path: diffraction_utils
          ref: ${{ github.ref_name }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate Report
        run: |
          python -m pip install --upgrade pip
          pip install -r diffraction_utils/requirements.txt
          pip install -e diffraction_utils
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
          pytest --cov=./ --cov-report=xml
          coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DiamondLightSource/islatu